#!/bin/bash

yellow='\033[0;33m'
no_color='\033[0m'

# Exit if this was a file checkout, not a branch change ($3 == 1)
[[ $3 == 0 ]] && exit 0

git pull
function changed() {
    git diff --name-only $1 $2 | grep "^$1" >/dev/null 2>&1
}

if changed 'composer.lock'; then
    echo -e "${yellow}composer.lock is changed, running install command...${no_color}"
    docker exec -t accounts composer install
fi
