apiVersion: v1
kind: ConfigMap
metadata:
  name: accounts
data:
  APP_ENV: "production"
  APP_DEBUG: "true"
  APP_LOG_LEVEL: "debug"
  DB_CONNECTION: "pgsql"
  DB_HOST: "rds-production.joinr.com"
  DB_USERNAME: "postgres"
  DB_DATABASE: "production"
  DB_SCHEMA: "accounts"
  CACHE_DRIVER: "redis"
  CACHE_TTL: "3600"
  REDIS_HOST: "redis-service"
  LOG_CHANNEL: "errorlog"
  AUTH0_DOMAIN: "https://joinr-production.us.auth0.com"
  AUTH0_CLIENT_ID: "jAZoz9u3RQ8zOh4EFzXOoVC1jHFYq6et"
  CONNECT_MS_URL: "https://connect.joinr.com/"