apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qa

bases:
  - ../../base

resources:
- external-secrets.yaml
- configmap.yaml
- namespace.yaml
- ingress.yaml

patchesStrategicMerge:
  - deployment.yaml
  - external-secrets.yaml
  - redis.yaml